### ISSUE TITLE
Investigating how OPTIONS is handled today

### ISSUE THREAD

**Issue by ijmitch** [ijmitch/cicscors#2]
Looking at a trace, we can see:

```
00062 SO    WB 0432 WBRQ  *EXC* OPTIONS NOT OPTIONS *                       RET-ABCCB19C 18:30:02.7982353618 00.0000073339 =000328=
00062 QR    WB 0501 WBSR  EXIT  RECEIVE/EXCEPTION REASON(OPTIONS_NOT_ALLOWED) ATTACH_TRANSID() FAILING_PROGRAM() CONNECTION_PERSIST
                                (YES) TOKEN(2AFA6030)                       RET-ABCCB19C 18:30:02.7982397753 00.0000044135 =000329=
00062 QR    AP 4522 WBXN  *EXC* RECEIVE_ERROR                               RET-A9D583CE 18:30:02.7982404086 00.0000006333 =000330=
```

and then CICS links to the [Web Error Program](https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.3.0/com.ibm.cics.ts.internet.doc/topics/dfhtlbv.html#dfhtlbv).

```
PG 0A01 PGLU  ENTRY - FUNCTION(LINK_URM) PROGRAM_NAME(DFHWBEP) COMMAREA(2AF9D4D0 , 000000D0) SYSTEM_AUTOINSTALL(NO)
 
              TASK-00062 KE_NUM-004D TCB-C/QR   /009B3E88 RET-ABCCDA56 TIME-18:30:02.7988260195 INTERVAL-00.0000008598      =000368=
                1-0000  00400000 0000009D 00000000 00000000  BD100000 00000000 01000100 C4C6C8E6  *. ..........................DFHW*
                  0020  C2C5D740 2AF9D4D0 000000D0 29A18D00  02000000 00000000 00000000 00000000  *BEP .9M}...}....................*
                2-0000  00D06EA6 82859783 81400002 00420000  C1E6C2C1 000002FA 2AF9B878 000000E7  *.}>wbepca ......AWBA.....9.....X*
                  0020  2AFA7008 00000120 0CF94BF1 F4F54BF1  F7F84BF5 F2404040 08F94BF2 F04BF54B  *.........9.145.178.52   .9.20.5.*
                  0040  F0404040 40404040 E3C8D9C5 C1C4C1C3  00000000 00000000 00000000 00000000  *0       THREADAC................*
                  0060  00000000 00000000 00000195 00000000  00000000 00000000 00000000 D5000000  *...........n................N...*
                  0080  0CF94BF1 F4F54BF1 F7F84BF5 F2404040  40404040 40404040 40404040 40404040  *.9.145.178.52                   *
                  00A0  40404040 40404040 08F94BF2 F04BF54B  F0404040 40404040 40404040 40404040  *        .9.20.5.0               *
                  00C0  40404040 40404040 40404040 40404040
```

Unfortunately, this program is not provided with much HTTP request information, but we can see that the field wbep_message_number (offset x'14' in the commarea) is x'2FA' = 762. [DFHWB0762](https://www.ibm.com/support/knowledgecenter/en/SSGMGV_3.2.0/com.ibm.cics.ts.messages.doc/cics_mc/dfhwb/WB0762.html) is unique to the detection of an OPTIONS request that CICS doesn't know how to handle.

The description of the wbep_response_ptr field says...

*On input, pointer points to a block of storage containing the default HTTP response for this error. CICS provides only a default response for HTTP requests. The default response is a complete HTTP response, including a status line, HTTP headers and message body. On output, this pointer either points to the same block of storage, containing the original or a modified version of the default response, or a pointer to a new block of storage containing a replacement response. If DFHWBEP successfully uses the EXEC CICS WEB SEND command to create a new response and sends it to the web client, CICS ignores and discards the HTTP response in the block of storage. Otherwise, the response in the block of storage is sent to the web client.*

It sounds from that as if it *might* be possible to code some handling of OPTIONS into DFHWBEP. For example, if DFHWBEP could use the `EXEC CICS WEB EXTRACT PATH` command to discover the resource specified in the HTTP request, and then `EXEC CICS WEB SEND` a suitable, good reply to the request, then we might need to enhancement to CICS!

Actually, we might ignore the message number in the commarea and use `EXEC CICS WEB EXTRACT HTTPMETHOD` to know we're trying to handle an OPTIONS request.

**Comment by ijmitch** [comment]
I might try to knock something up to test this over the weekend

**Comment by ijmitch** [comment]
I modified DFHWBEP by adding an `EXEC CICS WEB SEND` and CICS was perfectly happy to turn the default `405 not allowed` into a `200 OK` with my response body.

I'll now try making this conditional on the request having been `OPTIONS`.

**Comment by ijmitch** [comment]
hmm... seems like we cannot do a `EXEC CICS WEB EXTRACT` to get the method :-(

**Comment by RussTeubner** [comment]
Can we dig the verb out using a technique other than Extract?

Sent from my iPhone with Siri's assistance (we do not always agree...
enjoy).

On Mar 11, 2017, at 12:00 PM, ijmitch <notifications@github.com> wrote:

hmm... seems like we cannot do a EXEC CICS WEB EXTRACT to get the method :-(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ijmitch/cicscors/issues/2#issuecomment-285895960>, or mute
the thread

**Comment by ijmitch** [comment]
I think DFHWBEP code would need both the verb and the resource/path in order to make some sensible response to an OPTIONS request.

I don't think CICS is currently setting up the environment for EXTRACT to be used before it links to DFHWBEP, so we would need a product enhancement to get this to work reasonably.

**Comment by RussTeubner** [comment]
I’m certainly not opposed to digging out the verb and uri from control
blocks --  on an interim basis to complete this POC.



*From:* ijmitch [mailto:notifications@github.com]
*Sent:* Sunday, March 12, 2017 5:20 AM
*To:* ijmitch/cicscors <cicscors@noreply.github.com>
*Cc:* RussTeubner <russ@hostbridge.com>; Comment <comment@noreply.github.com
>
*Subject:* Re: [ijmitch/cicscors] Investigating how OPTIONS is handled
today (#2)



I think DFHWBEP code would need both the verb and the resource/path in
order to make some sensible response to an OPTIONS request.

I don't think CICS is currently setting up the environment for EXTRACT to
be used before it links to DFHWBEP, so we would need a product enhancement
to get this to work reasonably.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ijmitch/cicscors/issues/2#issuecomment-285935288>, or mute
the thread

**Comment by ijmitch** [comment]
CICS is also issuing a message every time an OPTIONS request is received (as well as invoking the DFHWBEP program), so if we want to normalise this then that message needs suppressing as well.

**Comment by ijmitch** [comment]
I'm going to close this issue as I think I understand enough of the flow to know the optimism that DFHWBEP could be a quick route to a solution was misplaced. I'll open another one to discuss design for something the RFE might implement.
